name: 'Bot: Update flake inputs'

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    uses: ./.github/workflows/_update-flake-reusable.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      summary-title: 'Stable Update Summary'
    secrets:
      app-id: ${{ secrets.V01D42_DOTFILES_UPDATER_APP_ID }}
      private-key: ${{ secrets.V01D42_DOTFILES_UPDATER_PRIVATE_KEY }}
      cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
